version: '3.8'

services:
  app:
    container_name: app
    build:
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/projects
      - gradle-.gradle:/projects/.gradle
      - gradle-build:/projects/build
    ports:
      - "8080:8080"
    expose:
      - 8080
    working_dir: /projects
    command: gradle bootRun -x test

  front:
    container_name: front
    build:
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/projects
    ports:
      - "4200:4200"
    command: ng serve --host=0.0.0.0


  db:
    container_name: postgresql
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  postgres-data:
  gradle-.gradle:
  gradle-build:

