version: '3.8'

services:
  redis:
    image: redis:latest
    hostname: radis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    expose:
      - 6379

  app:
    build:
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/projects
    ports:
      - "8080:8080"
    expose:
      - 8080
    working_dir: /projects
    command: mvn spring-boot:run


  front:
    build:
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/projects
    ports:
      - "4200:4200"
    command: ng serve --host=0.0.0.0


  db:
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"


volumes:
  postgres-data:
  redis-data:

